// <auto-generated />
namespace WebApplication2
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class BookModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BookModel));
        
        string IMigrationMetadata.Id
        {
            get { return "201811261222304_BookModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
